
image:
  file: .gitpod.Dockerfile
arch: x86

    
# tasks:
#   - name: multi-repo-test
#     command: gp repo bilalafzal-ti/multi-repo-test

tasks:
  - name: multi-repo-test
    command: echo "1. Main configuration file's task running 3"

